// Package clone provides website cloning functionality.
//
// session.go: Cookie jar persistence for authenticated cloning.
// Saves browser cookies to a Netscape-format file and restores them
// on the next run, enabling cloning of sites behind login walls.
package clone

import (
	"bufio"
	"fmt"
	"net/http"
	"net/http/cookiejar"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"golang.org/x/net/publicsuffix"
)

// CloneSession manages HTTP cookies for authenticated website cloning.
// Cookies are persisted in Netscape HTTP Cookie File format, compatible
// with curl and most browsers.
type CloneSession struct {
	jar      *cookiejar.Jar
	filePath string
}

// NewCloneSession creates a session with optional cookie persistence.
// If filePath is empty, cookies are kept in memory only.
func NewCloneSession(filePath string) (*CloneSession, error) {
	jar, err := cookiejar.New(&cookiejar.Options{
		PublicSuffixList: publicsuffix.List,
	})
	if err != nil {
		return nil, fmt.Errorf("create cookie jar: %w", err)
	}

	s := &CloneSession{
		jar:      jar,
		filePath: filePath,
	}

	if filePath != "" {
		if err := s.load(); err != nil && !os.IsNotExist(err) {
			return nil, fmt.Errorf("load cookies: %w", err)
		}
	}

	return s, nil
}

// HTTPClient returns an *http.Client that uses the session's cookie jar.
func (s *CloneSession) HTTPClient() *http.Client {
	return &http.Client{
		Jar:     s.jar,
		Timeout: 60 * time.Second,
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			if len(via) >= 10 {
				return fmt.Errorf("too many redirects")
			}
			return nil
		},
	}
}

// SetCookies adds cookies for a given URL to the jar.
func (s *CloneSession) SetCookies(rawURL string, cookies []*http.Cookie) {
	u, err := url.Parse(rawURL)
	if err != nil {
		return
	}
	s.jar.SetCookies(u, cookies)
}

// Save persists cookies to the file in Netscape format.
func (s *CloneSession) Save() error {
	if s.filePath == "" {
		return nil
	}

	dir := filepath.Dir(s.filePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create cookie dir: %w", err)
	}

	f, err := os.Create(s.filePath)
	if err != nil {
		return fmt.Errorf("create cookie file: %w", err)
	}
	defer f.Close()

	// Netscape header.
	fmt.Fprintln(f, "# Netscape HTTP Cookie File")
	fmt.Fprintln(f, "# Generated by Wukong — do not edit manually")
	fmt.Fprintln(f, "")

	// Write all cookies from all domains.
	for _, c := range s.jar.Cookies(nil) {
		// The jar.Cookies(nil) returns cookies from all origins
		// when called with nil URL. Each cookie's Domain field
		// identifies its origin.
		fmt.Fprintf(f, "%s\t%s\t%s\t%s\t%d\t%s\t%s\n",
			defaultString(c.Domain, ".local"),
			"TRUE",
			defaultString(c.Path, "/"),
			strings.ToUpper(boolToStr(c.Secure)),
			c.MaxAge,
			c.Name,
			c.Value,
		)
	}

	return nil
}

// load reads cookies from the file in Netscape format.
func (s *CloneSession) load() error {
	f, err := os.Open(s.filePath)
	if err != nil {
		return err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.Split(line, "\t")
		if len(parts) < 7 {
			continue
		}

		domain := parts[0]
		path := parts[2]
		secure := strings.EqualFold(parts[3], "TRUE")
		name := parts[5]
		value := parts[6]

		// Build a URL from domain and path to set the cookie.
		scheme := "http"
		if secure {
			scheme = "https"
		}
		cookieURL := fmt.Sprintf("%s://%s%s", scheme, domain, path)
		u, err := url.Parse(cookieURL)
		if err != nil {
			continue
		}

		s.jar.SetCookies(u, []*http.Cookie{{
			Name:   name,
			Value:  value,
			Domain: domain,
			Path:   path,
			Secure: secure,
		}})
	}

	return scanner.Err()
}

func defaultString(s, def string) string {
	if s == "" {
		return def
	}
	return s
}

func boolToStr(b bool) string {
	if b {
		return "TRUE"
	}
	return "FALSE"
}
