// Package cli provides the "wukong init" command for initializing
// a wukong project directory with recommended structure and defaults.
package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

const (
	// initConfigTemplate is a minimal config template for new projects.
	initConfigTemplate = `# Wukong Configuration
# Generated by: wukong init
# Run "wukong configure" for interactive setup.

log_level: "info"
default_provider: "lmstudio"

providers:
  - name: "lmstudio"
    type: "lmstudio"
    api_key: "lmstudio"
    base_url: "http://localhost:1234/v1"
    model: "google/gemma-4-26b-a4b"

agent:
  max_llm_calls: 50
  max_tool_iterations: 30
  parallel_tools: true
  streaming: true
  temperature: 0.7
  max_tokens: 4096

security:
  permission_mode: "smart"
  block_dangerous_commands: true
  ignore_file_enabled: true
`

	// initInstructionsTemplate is the default Top of Mind instructions file.
	initInstructionsTemplate = `# Top of Mind Instructions
# Add persistent instructions here. They will be injected into
# the agent's system prompt for every conversation.
#
# Examples:
# - Always use Chinese to respond unless asked otherwise.
# - Prefer Go over Python for new projects.
# - Follow the Google C++ style guide for C++ code.
`
)

// newInitCmd creates the "wukong init" command for project
// initialization.
func newInitCmd() *cobra.Command {
	var targetDir string

	cmd := &cobra.Command{
		Use:   "init [directory]",
		Short: "Initialize a wukong project directory",
		Long: `Create the recommended directory structure and default
configuration for a wukong project.

Creates:
  .wukong/                  Project data directory
  .wukong/apps/             HTML applications
  .wukong/cache/            Browser cache
  .wukong/recipes/          Recipe definitions
  .wukong/skills/           Agent skill definitions
  .wukong/visuals/          Visualization output
  .wukong/instructions.md   Persistent agent instructions
  .wukongignore             File access blacklist
  config.yaml               Example configuration (if not exists)

Examples:
  wukong init
  wukong init my-project/
  wukong init --target ./my-workspace`,
		RunE: runInit,
		Args: cobra.MaximumNArgs(1),
	}

	cmd.Flags().StringVarP(
		&targetDir, "target", "t", "",
		"Target directory (default: current directory)")

	return cmd
}

func runInit(cmd *cobra.Command, args []string) error {
	targetDir, _ := cmd.Flags().GetString("target")

	// Determine target directory
	if len(args) > 0 {
		targetDir = args[0]
	}
	if targetDir == "" {
		var err error
		targetDir, err = os.Getwd()
		if err != nil {
			return fmt.Errorf("get current directory: %w", err)
		}
	}

	// Convert to absolute path for display
	absDir, err := filepath.Abs(targetDir)
	if err != nil {
		absDir = targetDir
	}

	// Create target directory if it doesn't exist
	if err := os.MkdirAll(targetDir, 0755); err != nil {
		return fmt.Errorf("create directory %q: %w", targetDir, err)
	}

	fmt.Printf("Initializing wukong project in: %s\n", absDir)
	fmt.Println()

	// Create .wukong directory structure
	dirs := []string{
		filepath.Join(targetDir, ".wukong"),
		filepath.Join(targetDir, ".wukong", "apps"),
		filepath.Join(targetDir, ".wukong", "cache"),
		filepath.Join(targetDir, ".wukong", "recipes"),
		filepath.Join(targetDir, ".wukong", "skills"),
		filepath.Join(targetDir, ".wukong", "visuals"),
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("create %q: %w", dir, err)
		}
		if _, err := os.Stat(dir); err == nil {
			fmt.Printf("  ✓ %s/\n", dir)
		}
	}

	fmt.Println()

	// Create .wukongignore
	ignorePath := filepath.Join(targetDir, ".wukongignore")
	_ = os.WriteFile(ignorePath, []byte(initIgnoreTemplate), 0644)
	fmt.Printf("  ✓ %s\n", ".wukongignore")

	// Create .wukong/instructions.md
	instPath := filepath.Join(targetDir, ".wukong", "instructions.md")
	_ = os.WriteFile(instPath, []byte(initInstructionsTemplate), 0644)
	fmt.Printf("  ✓ %s\n", ".wukong/instructions.md")

	// Create config.yaml only if not exists (don't overwrite)
	configPath := filepath.Join(targetDir, "config.yaml")
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		_ = os.WriteFile(configPath, []byte(initConfigTemplate), 0644)
		fmt.Printf("  ✓ %s (example configuration)\n", "config.yaml")
	} else {
		fmt.Printf("  - %s (already exists, skipped)\n", "config.yaml")
	}

	fmt.Println()
	fmt.Println("Project initialized successfully!")
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Println("  1. Edit config.yaml to configure your LLM provider")
	fmt.Println("  2. Run: wukong configure     (interactive setup)")
	fmt.Println("  3. Run: wukong session        (start a conversation)")
	fmt.Println("  4. Run: wukong session --provider openai --model gpt-4o")
	fmt.Println()
	fmt.Println("Add persistent instructions in .wukong/instructions.md")
	fmt.Println("Create agent skills in .wukong/skills/")

	return nil
}

const initIgnoreTemplate = `# Wukong Ignore File
# Prevent the agent from reading or modifying these files/directories.
# Uses gitignore-compatible syntax.

# Secrets and credentials
.env
.env.*
*.key
*.pem
*-key.json
credentials.*
secrets/

# Version control internals
.git/

# Sensitive system files
/etc/
/boot/
/sys/
/proc/

# Package manager locks
package-lock.json
yarn.lock
pnpm-lock.yaml
Gemfile.lock
Cargo.lock

# Node modules
node_modules/

# IDE and editor files
.idea/
.vscode/
*.swp
*.swo
*~

# Build artifacts
dist/
build/
target/
`
